Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py", line 4, in <module>
    print(messages[random.randint(0, 9)])
IndexError: list index out of range

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
Concentrate and ask again

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
It is decidedly so

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
It is certain

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
Concentrate and ask again

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/magic8Ball2.py ======
Yes definitely
eggs [1, 2, 3]
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    eggs [1, 2, 3]
NameError: name 'eggs' is not defined
eggs = [1, 2, 3]
eggs = [4, 5, 6]
eggs
[4, 5, 6]

=== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/passingReference.py ===
[1, 2, 3, 'Hello', 'Hello']

=== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/passingReference.py ===
[1, 2, 3, 'Hello']

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLoot.py ======
Inventory:
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLoot.py", line 20, in <module>
    print(str(total(inv, 'gold coin')))
NameError: name 'total' is not defined
spam.index('hello')
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    spam.index('hello')
NameError: name 'spam' is not defined
spam = 'hello'
spam.index('hello')
0
inv = {'gold coin': 42, 'rope':1}
list(inv)
['gold coin', 'rope']
list(inv())
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    list(inv())
TypeError: 'dict' object is not callable
newInv = list(inv.items())

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
[('gold coin', 42), ('rope', 1)]

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
[('gold coin', 42), ('rope', 1)]
Convert dictionary to list ['gold coin', 'rope']

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
[('gold coin', 42), ('rope', 1)]
Convert dictionary to list ['gold coin', 'rope']
Convert dictionary to list [42, 1]

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
[('gold coin', 42), ('rope', 1)]
Convert dictionary to list ['gold coin', 'rope']
Convert dictionary to list [42, 1]

====== RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLoot.py ======
Inventory:
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLoot.py", line 20, in <module>
    print(str(total(inv, 'gold coin')))
NameError: name 'total' is not defined

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
[('gold coin', 42), ('rope', 1)]
{'gold coin': 42, 'rope': 1}

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py", line 3, in <module>
    newInv = list(inv.items())
NameError: name 'inv' is not defined. Did you mean: 'int'?

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py", line 3, in <module>
    newDragonLoot = list(newDragonLoot.items())
NameError: name 'newDragonLoot' is not defined. Did you mean: 'dragonLoot'?

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py", line 3, in <module>
    newDragonLoot = list(DragonLoot.items())
NameError: name 'DragonLoot' is not defined. Did you mean: 'dragonLoot'?

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py", line 3, in <module>
    newDragonLoot = list(dragonLoot.items())
AttributeError: 'list' object has no attribute 'items'

= RESTART: /Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py =
Traceback (most recent call last):
  File "/Users/nurfatimah.zainuddinkaligo.com/Documents/dragonLootPseudoCode.py", line 6, in <module>
    newDragonLoot = list(dragonLoot.items())
AttributeError: 'list' object has no attribute 'items'
